name: Selenium Test Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Install Display
        shell: pwsh
        run: |
          choco install -y selenium-all-drivers

      - name: Configure Windows Display Settings
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' -Name 'VisualFXSetting' -Value 2

      - name: Run Tests
        continue-on-error: false
        env:
          DISPLAY: :99
          SELENIUM_HEADLESS: true
        run: |
          mvn clean test -Dwebdriver.chrome.whitelistedIps="" -Dwebdriver.chrome.args="--no-sandbox,--disable-dev-shm-usage,--headless,--disable-gpu,--window-size=1920,1080" -Dwebdriver.firefox.args="--headless"

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            target/surefire-reports
            target/allure-results
            target/allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report

      - name: Archive Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-failure-screenshots
          path: |
            **/screenshots
            **/test-output

      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/surefire-reports/TEST-*.xml'

      - name: Send Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Selenium Test Run Completed"
          SLACK_TITLE: "Test Results"
          SLACK_COLOR: ${{ job.status }}