name: Selenium Test Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Install Display
        shell: pwsh
        run: |
          choco install -y selenium-all-drivers

      - name: Configure Windows Display Settings
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' -Name 'VisualFXSetting' -Value 2

      - name: Run Tests
        continue-on-error: false
        env:
          DISPLAY: :99
          SELENIUM_HEADLESS: true
        run: |
          mvn clean test allure:report
        shell: bash
